# Generated by Django 5.1.3 on 2024-11-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reading_time",
                    models.IntegerField(
                        choices=[
                            (15, "15 minutes"),
                            (30, "30 minutes"),
                            (45, "45 minutes"),
                            (60, "60 minutes"),
                            (75, "75 minutes"),
                            (90, "90 minutes"),
                            (105, "105 minutes"),
                        ]
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[("undergrad", "Undergraduate"), ("grad", "Graduate")],
                        max_length=10,
                    ),
                ),
                (
                    "paper_recency",
                    models.CharField(
                        choices=[
                            ("6m", "6 months"),
                            ("1yr", "1 year"),
                            ("3yr", "3 years"),
                            ("any", "Anytime"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("url", models.URLField()),
                ("authors", models.CharField(max_length=300)),
                (
                    "paper_filter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.paperfilter",
                    ),
                ),
                (
                    "research_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.researchtopic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("courses", models.JSONField()),
                (
                    "liked_papers",
                    models.ManyToManyField(related_name="liked_by", to="app.paper"),
                ),
            ],
        ),
    ]
