# Generated by Django 5.1.3 on 2024-11-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_author_remove_user_liked_papers_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="paper_filter",
        ),
        migrations.AddField(
            model_name="paper",
            name="difficulty_level",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="paper_recency",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="reading_time",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="papers_liked",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to="app.paper"
            ),
        ),
        migrations.DeleteModel(
            name="PaperFilter",
        ),
    ]
