# Generated by Django 5.1.3 on 2024-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_paper_paper_filter_paper_difficulty_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="difficulty_level",
            field=models.CharField(
                choices=[("undergrad", "Undergraduate"), ("grad", "Graduate")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="paper_recency",
            field=models.CharField(
                choices=[
                    ("6m", "6 months"),
                    ("1yr", "1 year"),
                    ("3yr", "3 years"),
                    ("any", "Anytime"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="reading_time",
            field=models.IntegerField(
                choices=[
                    (15, "15 minutes"),
                    (30, "30 minutes"),
                    (45, "45 minutes"),
                    (60, "60 minutes"),
                    (75, "75 minutes"),
                    (90, "90 minutes"),
                    (105, "105 minutes"),
                ]
            ),
        ),
    ]
