# Generated by Django 5.1.3 on 2024-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_paper_difficulty_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="courses",
        ),
        migrations.AddField(
            model_name="user",
            name="courses",
            field=models.ManyToManyField(related_name="users", to="app.course"),
        ),
    ]
