# Generated by Django 5.1.3 on 2024-11-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_course_remove_user_courses_user_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
