# Generated by Django 5.1.3 on 2024-11-09 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_course_description_course_course_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="paper",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="user",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="research_topic",
        ),
        migrations.RemoveField(
            model_name="user",
            name="papers_liked",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="difficulty_level",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="name",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="paper_recency",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="reading_time",
        ),
        migrations.AddField(
            model_name="paper",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="research_interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                to="app.researchinterest",
            ),
        ),
        migrations.CreateModel(
            name="UserLikedPapers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_by_users",
                        to="app.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "paper")},
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reading_time",
                    models.IntegerField(
                        choices=[
                            (15, "15 minutes"),
                            (30, "30 minutes"),
                            (45, "45 minutes"),
                            (60, "60 minutes"),
                            (75, "75 minutes"),
                            (90, "90 minutes"),
                            (105, "105 minutes"),
                            (120, "120 minutes"),
                        ]
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("graduate", "Graduate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "paper_recency",
                    models.CharField(
                        choices=[
                            ("6 months", "6 months"),
                            ("1 year", "1 year"),
                            ("3 years", "3 years"),
                            ("5 years", "5 years"),
                            ("anytime", "Anytime"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "research_interest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.researchinterest",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("university", models.CharField(max_length=255)),
                ("major", models.CharField(max_length=100)),
                (
                    "courses",
                    models.TextField(help_text="Comma-separated list of courses"),
                ),
                (
                    "research_interests",
                    models.ManyToManyField(
                        related_name="users", to="app.researchinterest"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.AddField(
            model_name="paper",
            name="authors",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="ResearchTopic",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
