# Generated by Django 5.1.3 on 2024-11-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_userpreference_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="difficulty_level",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="paper_recency",
            field=models.CharField(max_length=20),
        ),
    ]
