# Generated by Django 5.1.3 on 2024-11-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_summary',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
